title: Ase Morales - Full-stack Developer and Software Engineer
email: asemorales.tech@gmail.com
description: Full-stack developer and software engineer building scalable, fast, and secure web apps.
baseurl: ""
url: "https://asemorales.me"
author: Irish Danielle (Ase) Morales
social:
  name: Irish Danielle (Ase) Morales
  links:
    - https://github.com/IrishMorales
    - https://www.linkedin.com/in/irish-danielle-morales
keywords: "portfolio, freelance, full-stack developer, software engineer, web apps"

# Site structure
collections:
  works:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image:
        path: /assets/images/og-image.png
        height: 1200
        width: 630

# GitHub Pages ignores Gemfile plugins, so make sure any plugins added there are also
# added to the plugins here:
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
