services:
  - name: Web & Mobile Development
    icon-class: ri-device-fill
    text: Full-stack web developer doing mobile apps on the side, with experience from startups to enterprise microservices.
  - name: Scalable, fast, secure systems
    icon-class: ri-flashlight-fill
    text: I focus on system design & security, and I'm most passionate about helping systems scale and thrive long-term.
  - name: Developer & Designer
    icon-class: ri-code-line
    text: I mainly do backend-heavy development professionally, frontend-heavy projects for freelance, & volunteer designs for nonprofits.
  - name: Open Source Enthusiast
    icon-class: ri-heart-3-fill
    text: I believe in open & accessible knowledge — I am where I am today because of the people & opportunities that have helped me, and I hope to do the same :)
